### ISSUE TITLE
Límite de títulos y centrado de barras

### ISSUE THREAD

**Issue by ocewen** [JoseAntonioLpz/lpzJS#11]
Los títulos descriptivos que aparecen debajo de las barras deben de ser configurables por el usuario en longitud y no estar capados. También se debería permitir al usuario el poder centrar o alinear esos títulos al width máximo de la barra. Adjunto ejemplo.
![ejemplo_barras](https://user-images.githubusercontent.com/40170680/74729838-63defa80-5245-11ea-875d-da943a826049.PNG)

**Comment by JoseAntonioLpz** [comment]
Listo para la siguiente versión
