### ISSUE TITLE
Mejora visual en gráfico de barras

### ISSUE THREAD

**Issue by ocewen** [JoseAntonioLpz/lpzJS#12]
Estaría bien incluir líneas descriptivas detrás de las barras, por ejemplo de 5 en 5 valores ( o configurables por el usuario ) para así permitir una mejor visualización de los gráficos.
Incluyo adjunto para una mejor comprensión.
![barras_limites](https://user-images.githubusercontent.com/40170680/74730070-c7692800-5245-11ea-8737-c474ce7c796b.PNG)

**Comment by JoseAntonioLpz** [comment]
En la siguiente versión está listo
