### ISSUE TITLE
Mejoras en las barras

### ISSUE THREAD

**Issue by ocewen** [JoseAntonioLpz/lpzJS#14]
Las barras muestran hasta ahora el valor que se le pasa en el data-json en el campo **value** . 

1. En primer lugar, debería de existir un tercer parámetro que permita pasar un string a mostrar en las barras y no mostrar solo el value, ya que no siempre se pasa un valor fijo por ejemplo "7". Muchas veces se pasa un valor string como "24 unidades".

2. El usuario debería poder mostrar o no ese value dentro de las barras. Sería recomendable que se pudiera mostrar los values al poner el ratón o cualquier otro tipo de foco en la barra. Adjunto imagen.
![barras_info](https://user-images.githubusercontent.com/40170680/74731046-91c53e80-5247-11ea-93a9-66aacc5b0648.png)

3. No siempre se suele usar el mismo color para toda la barra. En ocasiones se usa un degradado de color para indicar los valores de las barras. Estaría bien incluir esta mejora.

4. Las barras deberían de tener la opción de autoescalar según el ancho disponible y el número de barras a dibujar. Esto lo considero bastante importante a ojos de un cliente que vaya a consumir un informe con estos gráficos.

**Comment by JoseAntonioLpz** [comment]
En desarrollo

**Comment by JoseAntonioLpz** [comment]
- [X] Opcion autoescalar ancho en graficas de barras (Proximamente en las demas y barras de progreso)
- [X] Hover sobre la barra
- [X] Tercer valor en el JSON (Opcional)
- [x] Colores de la barra
