### ISSUE TITLE
Error de visualización

### ISSUE THREAD

**Issue by ocewen** [JoseAntonioLpz/lpzJS#15]
Dentro de una gráfica de barras cuando una de las barras supera x línea de datos la oculta. El número de la lína debería de aparecer a la izquierda de la línea y no en la gráfica. Adjunto imagen.
![numeraciones](https://user-images.githubusercontent.com/40170680/74813179-32256c80-52f5-11ea-9dbb-a9cdccbe2a8f.PNG)

**Comment by JoseAntonioLpz** [comment]
Resulto en la proxima actualización
